POST http://localhost:3000/contacts
Content-Type: application/json

{"firstName":"Kemo","lastName":"Sabe","phoneNumber":"6428999544", "email": "ksab@test.com"}
###

GET http://localhost:3000/contacts
###

PATCH http://localhost:3000/contacts/3136302b-d448-4955-b142-0cfa81378454?email=em@test.com
###

DELETE http://localhost:3000/contacts/6a572a4b-7b18-4809-84ef-1b121f8cdd85
###

GET http://localhost:4000/contacts/export