POST http://localhost:4000/contacts
Content-Type: application/json

{"firstName":"Emeka","lastName":"Ike","phoneNumber":"64112899"}
###

GET http://localhost:4000/contacts
###

PATCH http://localhost:4000/contacts/357e9b02-2902-4148-b63d-c9c8fc741643?firstName=Tunde
###

DELETE http://localhost:4000/contacts/IOK57CDUY0Bx5EYU3kQx
###

GET http://localhost:4000/contacts/export